name: pytesmo-docs
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - pandas
  - netcdf4
  - cython
  - matplotlib
  - basemap
  - pybufr-ecmwf
  - pygrib
  - pykdtree
  - pyresample
  - pyproj
  - ipython
  - ipyparallel
  - python=3.6
  - pip:
      - pygeobase
      - pygeogrids
      - ascat
